services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 1s
      retries: 10

  redis:
    image: redis
    volumes:
      - ./.data/redis:/data

  migrations:
    build: . 
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  web:
    build: . 
    command: sh -c "uvicorn project.asgi:application --host 0.0.0.0 --port 8000 --reload --reload-include \"*.html\" --reload-include=\"*.txt\" --log-level info"
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - REDIS_HOST=redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully